#!/bin/bash

wid=$(xdotool search --classname todo)

if [ -z "$wid" ]; then
    emacs $HOME/jrnl/TODO.org
    wid=$(xdotool search --classname emacs)
    xdotool windowfocus $wid
    xdotool key Control_L+1
elif [ -z "$(xdotool search --onlyvisible --classname emacs 2>/dev/null)" ]; then
  xdotool windowmap $wid
  xdotool windowfocus $wid
else
  xdotool windowunmap $wid
fi
