#!/bin/bash

keepassProcess=$(pidof keepassx2)

if [[ -z $keepassProcess ]]; then
  #if it was accidentally killed, spawn again
  keepassx2 &
  sleep 1
  kpWid=$(pfw)
  echo $kpWid > /tmp/keepasswindow
else
  #process exists, toggle visibility
  mapw -t $(cat /tmp/keepasswindow)
fi ;
